# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='pay_from',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_made', to='project.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='pay_to',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accepted', to='project.User'),
            preserve_default=False,
        ),
    ]
