# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180824_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='users_bidded',
        ),
        migrations.AddField(
            model_name='task',
            name='offers',
            field=models.ManyToManyField(related_name='users_bidded', to='project.User'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
