# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180426_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='/media/no_image.jpg', upload_to='media/'),
        ),
    ]
