# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-24 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180824_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='offers',
            new_name='users_bidded',
        ),
    ]
