# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180427_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='/no_image.jpg', upload_to='media/'),
        ),
    ]
