# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180427_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users_bidded',
        ),
        migrations.AddField(
            model_name='task',
            name='users_bidded',
            field=models.ManyToManyField(related_name='tasks', to='project.User'),
        ),
    ]
