# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180824_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='project.Task'),
        ),
    ]
