# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-26 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180826_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='stripe_charge_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
