# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180427_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to='project.User'),
            preserve_default=False,
        ),
    ]
