# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_review_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/no_image.jpg', upload_to='media/'),
        ),
    ]
