# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180514_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tasks',
        ),
        migrations.AddField(
            model_name='cart',
            name='tasks',
            field=models.ManyToManyField(null=True, related_name='cart', to='project.Task'),
        ),
    ]
